### PR TITLE
Update CoreModule.java

### PR DESCRIPTION
**Pull request by Cewlt**
added a few things such as [UUID] [IP-ADDRESS] [NICKNAME] [UNIQUE] for the MOTD.

[UUID] returns the players UUID, obv.

[IP-ADDRES] returns the players IP in string format.

[NICKNAME] returns the players displayname which is grabbed using TrilliumPlayer

[UNIQUE] returns how many players have joined the server total, using getOfflinePlayers + getOnlinePlayers, it does not require any external storage.

### CODE REVIEW

**Comment by LordSaad44** [comment]
Merged :)

**Comment by Cewlt** [comment]
accept my skype request? skype: cheetos94444

**Comment by LordSaad44** [comment]
If skype mobile lets me... I'm on the bus on my way to school

**Comment by LordSaad44** [comment]
I don't see a request on mobile skype. Also can't find cheetos194444.
Double check you got the username right: saadodi58

**Comment by Cewlt** [comment]
okay, just accept it whenever :)

btw, your skype say's you're in Lebanon, which would mean GMT+3 time zone, is this correct? as you're currently on your way to school and I may be going to bed soon, I think time zones might get a little messy so I wanna see if I can work out a sleep schedule for myself where I am awake during or around the time you are available.

Skype is "cheetos94444" no "1" in it :)

**Comment by LordSaad44** [comment]
Yeah i'm in lebanon and the timeshift from me to america is >= 6 hours. Are
you sure you want to adjust your sleep schedule? Most people i know can't
be bothered or have plans in the day.

Thanks for pointing out the typo. Still can't find you because skype mobile
is shit \^-^/

**Comment by LordSaad44** [comment]
I'll try adding you to the github repo

**Comment by Cewlt** [comment]
ah, i'm home-schooled so essentially it doesn't matter when I complete my school work as long as I get it all finished every week.

You can wait till you get back on a PC, I will be falling asleep soon anyways. 

Talk tomorrow :)

**Comment by LordSaad44** [comment]
Ok :) i sent the github repo invite

**Comment by LordSaad44** [comment]
http://i.imgur.com/pjwxAOf.png :( I'm not doing it wrong...

**Comment by Cewlt** [comment]
hmm, check if you have me blocked

https://support.skype.com/en/faq/FA12196/why-do-i-see-blocked-contacts-in-skype-for-modern-windows?

**Pull request merged**
